package HealthSystem;


/**
* HealthSystem/_HealthServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HealthMonitor.idl
* Thursday 01 May 2025 3:33:16 PM
*/

public class _HealthServiceStub extends org.omg.CORBA.portable.ObjectImpl implements HealthSystem.HealthService
{

  public void sendData (String patientId, float temperature, float heartRate, float spo2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendData", true);
                $out.write_string (patientId);
                $out.write_float (temperature);
                $out.write_float (heartRate);
                $out.write_float (spo2);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sendData (patientId, temperature, heartRate, spo2        );
            } finally {
                _releaseReply ($in);
            }
  } // sendData

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HealthSystem/HealthService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _HealthServiceStub
