package HealthSystem;


/**
* HealthSystem/HealthService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HealthMonitor.idl
* Thursday 01 May 2025 3:33:16 PM
*/

public interface HealthService extends HealthServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HealthService
