package HealthSystem;

/**
* HealthSystem/HealthServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HealthMonitor.idl
* Thursday 01 May 2025 3:33:16 PM
*/

public final class HealthServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public HealthSystem.HealthService value = null;

  public HealthServiceHolder ()
  {
  }

  public HealthServiceHolder (HealthSystem.HealthService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HealthSystem.HealthServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HealthSystem.HealthServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HealthSystem.HealthServiceHelper.type ();
  }

}
