package HealthSystem;


/**
* HealthSystem/HealthServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HealthMonitor.idl
* Thursday 01 May 2025 3:33:16 PM
*/

abstract public class HealthServiceHelper
{
  private static String  _id = "IDL:HealthSystem/HealthService:1.0";

  public static void insert (org.omg.CORBA.Any a, HealthSystem.HealthService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HealthSystem.HealthService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (HealthSystem.HealthServiceHelper.id (), "HealthService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HealthSystem.HealthService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HealthServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HealthSystem.HealthService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static HealthSystem.HealthService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HealthSystem.HealthService)
      return (HealthSystem.HealthService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HealthSystem._HealthServiceStub stub = new HealthSystem._HealthServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static HealthSystem.HealthService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HealthSystem.HealthService)
      return (HealthSystem.HealthService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HealthSystem._HealthServiceStub stub = new HealthSystem._HealthServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
